language: node_js
node_js:
  - "lts/*"

script:
  - yarn run lint
  - yarn run test

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH="$HOME/.yarn/bin:$PATH"

